### ISSUE TITLE
[FEATURE] meta title and meta description support in useCms composable

### ISSUE THREAD

**Issue by mkucmus** [vuestorefront/shopware-pwa#1816]
### Description

Shopware PWA as a nuxt.js based application can take advantage of dynamic meta information within a page.
Meta title and meta description are present in the page resolver's response within product and category entity.

useCms composable is a place responsible for extracting page's data on dynamic pages (based on Shopware 6 routing).
related: #1739

### Acceptance criteria
- [ ] Investigation what's inside the page resolver's response using swagger docs or real world request via postman/browser network tab is made.
- [ ] CmsPage / Category / Product interfaces/types in @shopware-pwa/common package are consistent with that received from store-api (see  https://github.com/vuestorefront/shopware-pwa/blob/master/packages/commons/interfaces/models/content/cms/CmsPage.ts#L111)
- [ ] a computed property for metaDescription and metaTitle are created
- [ ] tests for useCms composable are aligned with the new format of composable

**Comment by mstegmeyer** [comment]
Not only categories, landing pages should be considered as well.

**Comment by mkucmus** [comment]
closed via #1739
