### ISSUE TITLE
[FEATURE] seo meta data support for landingpages

### ISSUE THREAD

**Issue by mkucmus** [vuestorefront/shopware-pwa#1863]
### Description

Seo meta-data is not available in `useCms` composable for pages in type "langing page". 
From short investigation, the data is not presented in the response from API so it cannot be available anyway.

related: #1739 

### Acceptance criteria

- [ ] double check the API response in few scenarios (association needed?)
- [ ] extract expected data to be available in meta* related refs
- [ ] create an issue in core API in case it's a problem on API side

**Comment by meeshoogendoorn** [comment]
@mkucmus does this mean that it's not possible to get meta info for landing page with the initial api call but a second one is required to get the meta info by `landingPage id` with the built-in endpoint? Are there any plans to fix this in `swagShopwarePWA` plugin? that could be a solution right?

**Comment by meeshoogendoorn** [comment]
FOUND the issue at swagShopware PWA, just overlooked it 👍
